import { lazy } from "react";
import type { ToolDefinition } from "@/core/tool-kit/types";

/**
 * Authoritative registry of all tools in The Big Bro's NetSec Armoury.
 * Read by the sidebar, home dashboard, search bar, and tool router.
 */
export const tools: ToolDefinition[] = [
  // --- Network Tools (Phase 4) ---
  {
    id: "internet-speed",
    name: "Internet Speed Test",
    description: "Measure real-time download bandwidth, upload capacity, and network latency.",
    category: "network",
    requiresServer: true,
    sequenceNumber: "#001",
    complexity: "basic",
    tags: ["network", "speed", "bandwidth", "latency"],
    Component: lazy(() => import("@/tools/internet-speed/InternetSpeedTool")),
  },
  {
    id: "ip-lookup",
    name: "IP Lookup",
    description: "Resolve public IP address geolocation, Autonomous System Number (ASN), and ISP details.",
    category: "network",
    requiresServer: true,
    sequenceNumber: "#002",
    complexity: "basic",
    tags: ["network", "ip", "geolocation", "asn"],
    Component: lazy(() => import("@/tools/ip-lookup/IpLookupTool")),
  },
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    description: "Analyze authoritative DNS records including A, AAAA, MX, TXT, NS, and CNAME.",
    category: "network",
    requiresServer: true,
    sequenceNumber: "#003",
    complexity: "intermediate",
    tags: ["network", "dns", "records", "nameserver"],
    Component: lazy(() => import("@/tools/dns-lookup/DnsLookupTool")),
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate CIDR prefixes, subnet masks, usable host ranges, and broadcast boundaries.",
    category: "network",
    requiresServer: false,
    sequenceNumber: "#004",
    complexity: "basic",
    tags: ["network", "subnet", "cidr", "ip-range"],
    Component: lazy(() => import("@/tools/subnet-calculator/SubnetCalculatorTool")),
  },
  {
    id: "port-checker",
    name: "Port Checker",
    description: "Verify service port connectivity and reachability with strict port allow-listing and SSRF protection.",
    category: "network",
    requiresServer: true,
    sequenceNumber: "#005",
    complexity: "intermediate",
    tags: ["network", "port", "firewall", "reachability"],
    Component: lazy(() => import("@/tools/port-checker/PortCheckerTool")),
  },
  {
    id: "ping-latency",
    name: "Ping / Latency Checker",
    description: "Calculate HTTP round-trip timing, jitter statistics, and server response distributions.",
    category: "network",
    requiresServer: true,
    sequenceNumber: "#006",
    complexity: "basic",
    tags: ["network", "ping", "latency", "jitter"],
    Component: lazy(() => import("@/tools/ping-latency/PingLatencyTool")),
  },

  // --- Cybersecurity Tools (Phase 5) ---
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate cryptographically secure passwords utilizing hardware-grade crypto.getRandomValues.",
    category: "cybersecurity",
    requiresServer: false,
    sequenceNumber: "#007",
    complexity: "basic",
    tags: ["cybersecurity", "password", "crypto", "generator"],
    Component: lazy(() => import("@/tools/password-generator/PasswordGeneratorTool")),
  },
  {
    id: "password-strength",
    name: "Password Strength Checker",
    description: "Evaluate password entropy, pattern heuristics, dictionary vulnerabilities, and estimated crack time.",
    category: "cybersecurity",
    requiresServer: false,
    sequenceNumber: "#008",
    complexity: "intermediate",
    tags: ["cybersecurity", "entropy", "strength", "audit"],
    Component: lazy(() => import("@/tools/password-strength/PasswordStrengthTool")),
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Compute cryptographic digests across MD5, SHA-1, SHA-256, SHA-384, and SHA-512 algorithms.",
    category: "cybersecurity",
    requiresServer: false,
    sequenceNumber: "#009",
    complexity: "basic",
    tags: ["cybersecurity", "hash", "sha256", "checksum"],
    Component: lazy(() => import("@/tools/hash-generator/HashGeneratorTool")),
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Token headers, claims, expiration timestamps, and payloads client-side.",
    category: "cybersecurity",
    requiresServer: false,
    sequenceNumber: "#010",
    complexity: "intermediate",
    tags: ["cybersecurity", "jwt", "token", "auth"],
    Component: lazy(() => import("@/tools/jwt-decoder/JwtDecoderTool")),
  },
  {
    id: "file-hash",
    name: "File Hash Checker",
    description: "Calculate and verify file checksum integrity hashes directly within the sandbox.",
    category: "cybersecurity",
    requiresServer: true,
    sequenceNumber: "#011",
    complexity: "intermediate",
    tags: ["cybersecurity", "file", "integrity", "checksum"],
    Component: lazy(() => import("@/tools/file-hash/FileHashTool")),
  },
  {
    id: "security-headers",
    name: "Security Header Analyzer",
    description: "Audit HTTP response security posture for CSP, HSTS, X-Frame-Options, and permission policies.",
    category: "cybersecurity",
    requiresServer: true,
    sequenceNumber: "#012",
    complexity: "advanced",
    tags: ["cybersecurity", "headers", "csp", "hsts", "audit"],
    Component: lazy(() => import("@/tools/security-headers/SecurityHeadersTool")),
  },
  {
    id: "binary-text",
    name: "Binary ⇄ Text Converter",
    description: "Bidirectional translation between standard UTF-8 text and formatted 8-bit binary bytecode.",
    category: "cybersecurity",
    requiresServer: false,
    sequenceNumber: "#013",
    complexity: "basic",
    tags: ["cybersecurity", "binary", "ascii", "encoding"],
    Component: lazy(() => import("@/tools/binary-text/BinaryTextTool")),
  },
];
